INSERT INTO tb_users (name, email, phone, password) VALUES ('João Silva', 'joao.silva@email.com', '123456789', 'senha123');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Maria Oliveira', 'maria.oliveira@email.com', '987654321', 'senha456');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Carlos Santos', 'carlos.santos@email.com', '111223344', 'senha789');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Ana Pereira', 'ana.pereira@email.com', '555666777', 'senhaABC');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Lucas Souza', 'lucas.souza@email.com', '999000111', 'senhaDEF');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Mariana Lima', 'mariana.lima@email.com', '222333444', 'senhaGHI');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Felipe Rocha', 'felipe.rocha@email.com', '777888999', 'senhaJKL');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Patricia Costa', 'patricia.costa@email.com', '444555666', 'senhaMNO');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Gustavo Silva', 'gustavo.silva@email.com', '111222333', 'senhaPQR');
INSERT INTO tb_users (name, email, phone, password) VALUES ('Juliana Santos', 'juliana.santos@email.com', '888999000', 'senhaSTU');

INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 1, 1);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 2, 2);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 5, 3);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 3, 4);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 4, 5);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 1, 6);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 3, 7);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 5, 8);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 3, 9);
INSERT INTO tb_orders (moment, order_status, client_id) VALUES (CURRENT_TIMESTAMP, 4, 10);

INSERT INTO tb_categories (name) VALUES ('Smartphone');
INSERT INTO tb_categories (name) VALUES ('Notebook');
INSERT INTO tb_categories (name) VALUES ('Tablet');
INSERT INTO tb_categories (name) VALUES ('Smartwatch');
INSERT INTO tb_categories (name) VALUES ('Fone bluetooth');
INSERT INTO tb_categories (name) VALUES ('Câmera digital');
INSERT INTO tb_categories (name) VALUES ('TV Smart');
INSERT INTO tb_categories (name) VALUES ('Console de videogame');
INSERT INTO tb_categories (name) VALUES ('Impressora multifuncional');
INSERT INTO tb_categories (name) VALUES ('Roteador Wi-Fi');
